#!/usr/bin/env bash
# Reads CATALOG.txt, pulls each repository's metadata from GitHub, and writes
# catalog-cache.tsv. Read-only: every call is a GET against the GitHub API
# through the gh CLI, using whatever login gh already has.
#
#   bash fetch-catalog.sh
#
# The cache is committed so the site can be rebuilt offline and so a diff shows
# exactly what changed upstream when a release lands.
set -uo pipefail

CATALOG_FILE="${CATALOG_FILE:-CATALOG.txt}"
CACHE_FILE="${CACHE_FILE:-catalog-cache.tsv}"

command -v gh >/dev/null 2>&1 || { echo "fetch: gh CLI not found" >&2; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "fetch: gh is not logged in — run 'gh auth login'" >&2; exit 1; }
[ -f "$CATALOG_FILE" ] || { echo "fetch: $CATALOG_FILE not found" >&2; exit 1; }

# category topic -> the label used on the site
category_of () {
  case "$1" in
    *bbst-business*)   printf 'Business' ;;
    *bbst-webapps*)    printf 'Web Apps' ;;
    *bbst-lightroom*)  printf 'Lightroom' ;;
    *bbst-geoscience*) printf 'Geoscience' ;;
    *)                 printf '' ;;
  esac
}

# platform topics -> "Windows · macOS", in a fixed order so it never reshuffles
platforms_of () {
  local t="$1" out=""
  case "$t" in *platform-windows*) out="Windows" ;; esac
  case "$t" in *platform-macos*)   out="${out:+$out · }macOS" ;; esac
  case "$t" in *platform-linux*)   out="${out:+$out · }Linux" ;; esac
  case "$t" in *platform-gpu*)     out="${out:+$out · }GPU" ;; esac
  case "$t" in *platform-plugin*)  out="${out:+$out · }Plugin" ;; esac
  case "$t" in *platform-library*) out="${out:+$out · }Python library" ;; esac
  case "$t" in *platform-web*)     out="${out:+$out · }Web" ;; esac
  printf '%s' "$out"
}

# an explicit status topic wins; otherwise releases decide
status_of () {
  local t="$1" tag="$2" pre="$3"
  case "$t" in
    *bbst-released*) printf 'released'; return ;;
    *bbst-beta*)     printf 'beta';     return ;;
    *bbst-private*)  printf 'private';  return ;;
    *bbst-dev*)      printf 'dev';      return ;;
  esac
  if [ -z "$tag" ]; then printf 'dev'
  elif [ "$pre" = "true" ]; then printf 'beta'
  else printf 'released'; fi
}

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
printf '# generated by fetch-catalog.sh — do not edit by hand\n' > "$tmp"
printf '# name\tslug\tcategory\tversion\tplatform\tstatus\tsummary\tlicense\trepo\n' >> "$tmp"

fail=0
# The cache already holds values GitHub cannot supply while repositories carry
# no description or topics. Read them back so a fetch refreshes what GitHub
# knows authoritatively — releases and licence — without discarding the rest.
PREV_CACHE="$(mktemp)"; cp "$CACHE_FILE" "$PREV_CACHE" 2>/dev/null || : 
cached () { awk -F'\t' -v s="$1" -v n="$2" '!/^#/ && $2==s {print $n; exit}' "$PREV_CACHE" 2>/dev/null; }

#  is in IFS because git may check this file out with CRLF endings; without it
# every last field carries a trailing carriage return and blank lines are not empty.
while IFS=$' \t\r' read -r repo slug sub _rest; do
  case "$repo" in ''|\#*) continue ;; esac
  [ -n "$slug" ] || slug="$(printf '%s' "${repo#*/}" | tr '[:upper:]_' '[:lower:]-')"

  p_name="$(cached "$slug" 1)"; p_cat="$(cached "$slug" 3)";  p_ver="$(cached "$slug" 4)"
  p_plat="$(cached "$slug" 5)"; p_stat="$(cached "$slug" 6)"; p_sum="$(cached "$slug" 7)"
  p_lic="$(cached "$slug" 8)"

  meta="$(gh api "repos/$repo" --jq '[.description // "", .license.spdx_id // "", (.topics // []|join(" "))]|@tsv' 2>/dev/null)"
  if [ -z "$meta" ]; then
    echo "fetch: cannot read $repo — private, renamed, or not accessible to this login" >&2
    fail=1; continue
  fi
  desc="$(printf '%s' "$meta" | cut -f1)"
  lic="$(printf '%s'  "$meta" | cut -f2)"
  topics="$(printf '%s' "$meta" | cut -f3)"

  # A repository with no releases returns 404, and gh prints the error body to
  # stdout, so the exit status is what decides — not whether output is empty.
  if rel="$(gh api "repos/$repo/releases/latest" --jq '[.tag_name // "", (.prerelease|tostring)]|@tsv' 2>/dev/null)"; then
    tag="$(printf '%s' "$rel" | cut -f1)"; pre="$(printf '%s' "$rel" | cut -f2)"
  else
    tag=""; pre="false"
  fi

  # "Display Name — summary" when a description is set; otherwise keep what the
  # cache already holds rather than falling back to a raw repository name.
  if [ -n "$desc" ]; then
    case "$desc" in
      *" — "*) name="${desc%% — *}"; summary="${desc#* — }"
               # Descriptions are authored naturally, so the half after the dash
               # may start lowercase. The roster shows it as a sentence under the
               # tool name, so lift the first letter for consistency across rows.
               summary="$(printf '%s' "${summary%"${summary#?}"}" | tr '[:lower:]' '[:upper:]')${summary#?}" ;;
      *) name="${p_name:-${repo#*/}}"; summary="$desc" ;;
    esac
  else
    name="${p_name:-${repo#*/}}"; summary="$p_sum"
    echo "fetch: $repo has no description — keeping the catalogued name and summary" >&2
  fi

  # Version: a release tag wins; otherwise keep what was catalogued.
  ver="${tag#v}"; [ -n "$ver" ] || ver="${p_ver:-—}"

  # A subpath entry is one app out of a repository holding several. Its name and
  # version come from that folder's Info.lua and its summary from its README,
  # because one repository description cannot describe two different plugins,
  # and a repository-wide release tag cannot version them separately.
  if [ -n "$sub" ]; then
    info="$(gh api "repos/$repo/contents/$sub/Info.lua" --jq '.content' 2>/dev/null | base64 -d 2>/dev/null)"
    if [ -z "$info" ]; then
      echo "fetch: $repo/$sub has no Info.lua" >&2; fail=1; continue
    fi
    name="$(printf '%s' "$info" | sed -n "s/.*LrPluginName *= *['\"]\([^'\"]*\)['\"].*/\1/p" | head -1)"
    vmaj="$(printf '%s' "$info" | sed -n 's/.*major *= *\([0-9]*\).*/\1/p' | head -1)"
    vmin="$(printf '%s' "$info" | sed -n 's/.*minor *= *\([0-9]*\).*/\1/p' | head -1)"
    vrev="$(printf '%s' "$info" | sed -n 's/.*revision *= *\([0-9]*\).*/\1/p' | head -1)"
    [ -n "$name" ] || { echo "fetch: $repo/$sub Info.lua has no LrPluginName" >&2; fail=1; continue; }
    ver="${vmaj:-0}.${vmin:-0}.${vrev:-0}"
    readme="$(gh api "repos/$repo/contents/$sub/README.md" --jq '.content' 2>/dev/null | base64 -d 2>/dev/null)"
    s="$(printf '%s' "$readme" | awk 'NR>1 && NF && !/^#/ {print; exit}' | sed 's/([^)]*)//g; s/`//g; s/\*\*//g; s/  */ /g; s/^ *//; s/ *$//' | cut -d. -f1)"
    if [ -n "$s" ] && [ "${#s}" -le 130 ]; then summary="$s"
    else
      summary="$p_sum"
      echo "fetch: $repo/$sub — README's opening line is unusable as a summary; keeping the catalogued one" >&2
    fi
  fi

  cat_label="$(category_of "$topics")"; [ -n "$cat_label" ] || cat_label="$p_cat"
  plat="$(platforms_of "$topics")";    [ -n "$plat" ] || plat="${p_plat:-—}"
  case "$topics" in
    *bbst-released*|*bbst-beta*|*bbst-private*|*bbst-dev*) stat="$(status_of "$topics" "$tag" "$pre")" ;;
    *) stat="${p_stat:-$(status_of "$topics" "$tag" "$pre")}" ;;
  esac
  case "$lic" in
    ""|NOASSERTION|null) lic="${p_lic:-Not stated}" ;;
  esac

  [ -n "$summary"   ] || { echo "fetch: $repo has no summary anywhere — set a description on GitHub" >&2; fail=1; }
  [ -n "$cat_label" ] || { echo "fetch: $repo has no category — add a bbst-<category> topic" >&2; fail=1; }

  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$name" "$slug" "$cat_label" "$ver" "$plat" "$stat" "$summary" "$lic" "$repo" >> "$tmp"
  printf '  %-26s %-30s %-9s %s\n' "$repo" "$name" "$ver" "$stat"
done < "$CATALOG_FILE"
rm -f "$PREV_CACHE"

if [ "$fail" != "0" ]; then
  echo "fetch: some repositories are incomplete; cache not replaced" >&2
  exit 1
fi
mv "$tmp" "$CACHE_FILE"; trap - EXIT
echo "fetch: wrote $CACHE_FILE"
