#!/usr/bin/env bash
# Refreshes the two facts about an app that are genuinely upstream: its latest
# release version and its declared licence. Everything else the site says —
# name, category, platform, status, summary — is authored in CATALOG.txt and is
# never touched here.
#
#   bash fetch-catalog.sh
#
# Read-only: every call is a GET against the GitHub API through the gh CLI,
# using whatever login gh already has. Most of the listed repositories are
# private, so this only works for a login that can see them.
#
# The cache is committed so the site can be rebuilt offline and so a diff shows
# exactly what moved upstream when a release lands.
set -uo pipefail

CATALOG_FILE="${CATALOG_FILE:-CATALOG.txt}"
CACHE_FILE="${CACHE_FILE:-catalog-cache.tsv}"

command -v gh >/dev/null 2>&1 || { echo "fetch: gh CLI not found" >&2; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "fetch: gh is not logged in — run 'gh auth login'" >&2; exit 1; }
[ -f "$CATALOG_FILE" ] || { echo "fetch: $CATALOG_FILE not found" >&2; exit 1; }

# Keep the previous cache readable while the new one is being built, so a
# repository that has gone unreachable keeps the version it last reported
# rather than silently losing it.
PREV_CACHE="$(mktemp)"
tmp="$(mktemp)"
trap 'rm -f "$tmp" "$PREV_CACHE"' EXIT
cp "$CACHE_FILE" "$PREV_CACHE" 2>/dev/null || :
cached () {  # slug field-index
  awk -F'\t' -v s="$1" -v n="$2" '!/^#/ && $1==s {print $n; exit}' "$PREV_CACHE" 2>/dev/null
}

printf '# generated by fetch-catalog.sh — do not edit by hand\n' > "$tmp"
printf '# Version and licence only. Everything else the site says lives in CATALOG.txt.\n' >> "$tmp"
printf '# slug\tversion\tlicense\n' >> "$tmp"

fail=0
# Split on tabs by hand rather than with IFS. Tab is an IFS *whitespace*
# character, so `read` collapses a run of them and an empty column — subpath, on
# every row that is not a Lightroom plugin — silently disappears, shifting every
# later field left. Trailing \r is stripped for the CRLF checkout case.
while IFS= read -r line; do
  line="${line%$'\r'}"
  case "$line" in ''|\#*) continue ;; esac
  rest="$line"
  slug="${rest%%$'\t'*}"; rest="${rest#*$'\t'}"
  repo="${rest%%$'\t'*}"; rest="${rest#*$'\t'}"
  sub="${rest%%$'\t'*}"
  [ -n "$repo" ] || { echo "fetch: $slug has no repository" >&2; fail=1; continue; }

  p_ver="$(cached "$slug" 2)"; p_lic="$(cached "$slug" 3)"

  lic="$(gh api "repos/$repo" --jq '.license.spdx_id // ""' 2>/dev/null)"
  if [ -z "$lic" ] && ! gh api "repos/$repo" --jq '.name' >/dev/null 2>&1; then
    echo "fetch: cannot read $repo — private, renamed, or not accessible to this login" >&2
    fail=1; continue
  fi
  case "$lic" in
    ""|NOASSERTION|null) lic="${p_lic:-Not stated}" ;;
  esac

  if [ -n "$sub" ]; then
    # One app out of a repository holding several — the Lightroom plugin
    # bundles. A repository-wide release tag cannot version two plugins
    # separately, so the version comes from the plugin's own Info.lua.
    info="$(gh api "repos/$repo/contents/$sub/Info.lua" --jq '.content' 2>/dev/null | base64 -d 2>/dev/null)"
    if [ -z "$info" ]; then
      echo "fetch: $repo/$sub has no Info.lua — keeping the catalogued version" >&2
      ver="${p_ver:-—}"
    else
      vmaj="$(printf '%s' "$info" | sed -n 's/.*major *= *\([0-9]*\).*/\1/p' | head -1)"
      vmin="$(printf '%s' "$info" | sed -n 's/.*minor *= *\([0-9]*\).*/\1/p' | head -1)"
      vrev="$(printf '%s' "$info" | sed -n 's/.*revision *= *\([0-9]*\).*/\1/p' | head -1)"
      ver="${vmaj:-0}.${vmin:-0}.${vrev:-0}"
    fi
  else
    # A repository with no releases returns 404, and gh prints the error body to
    # stdout, so the exit status is what decides — not whether output is empty.
    ver=""
    if tag="$(gh api "repos/$repo/releases/latest" --jq '.tag_name // ""' 2>/dev/null)"; then
      ver="${tag#v}"
    fi

    # A tag pushed without a GitHub Release still identifies a version, and
    # releases/latest 404s on it — which is how a production app ended up
    # published with no version at all. Fall back to the highest version-shaped
    # tag. Only bare `1.2.3` / `v1.2.3` tags count: a prefixed tag such as
    # `twoplugins-v1.8.1` belongs to one app inside a shared repository and is
    # not this repository's version. The tags API order is not documented as
    # sorted, so sort explicitly rather than trusting the first element.
    if [ -z "$ver" ]; then
      ver="$(gh api "repos/$repo/tags?per_page=100" --jq '.[].name' 2>/dev/null \
             | sed -n 's/^v\{0,1\}\([0-9][0-9.]*\)$/\1/p' | sort -V | tail -1)"
      [ -n "$ver" ] && echo "fetch: $repo has no published release — using tag v$ver" >&2
    fi
    [ -n "$ver" ] || ver="${p_ver:-—}"
  fi

  printf '%s\t%s\t%s\n' "$slug" "$ver" "$lic" >> "$tmp"
  printf '  %-26s %-9s %s\n' "$slug" "$ver" "$lic"
done < "$CATALOG_FILE"

if [ "$fail" != "0" ]; then
  echo "fetch: some repositories could not be read; cache not replaced" >&2
  exit 1
fi
mv "$tmp" "$CACHE_FILE"; trap 'rm -f "$PREV_CACHE"' EXIT
echo "fetch: wrote $CACHE_FILE"
